/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fitmix_sdk_common_OSLESMediaPlayer_OnCompletionListener */

#ifndef _Included_com_fitmix_sdk_common_OSLESMediaPlayer_OnCompletionListener
#define _Included_com_fitmix_sdk_common_OSLESMediaPlayer_OnCompletionListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
