/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fitmix_sdk_common_WatchTransMethods */

#ifndef _Included_com_fitmix_sdk_common_WatchTransMethods
#define _Included_com_fitmix_sdk_common_WatchTransMethods
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fitmix_sdk_common_WatchTransMethods
 * Method:    square
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_fitmix_sdk_common_WatchTransMethods_square
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_fitmix_sdk_common_WatchTransMethods
 * Method:    converToGPSJason
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_fitmix_sdk_common_WatchTransMethods_converToGPSJason
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_fitmix_sdk_common_WatchTransMethods
 * Method:    converToStepJason
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_fitmix_sdk_common_WatchTransMethods_converToStepJason
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring);

/*
 * Class:     com_fitmix_sdk_common_WatchTransMethods
 * Method:    converToLogJason
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_fitmix_sdk_common_WatchTransMethods_converToLogJason
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
