/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fitmix_sdk_common_OSLESMediaPlayer */

#ifndef _Included_com_fitmix_sdk_common_OSLESMediaPlayer
#define _Included_com_fitmix_sdk_common_OSLESMediaPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fitmix_sdk_common_OSLESMediaPlayer
 * Method:    createEngine
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fitmix_sdk_common_OSLESMediaPlayer_createEngine
  (JNIEnv *, jclass);

/*
 * Class:     com_fitmix_sdk_common_OSLESMediaPlayer
 * Method:    releaseEngine
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fitmix_sdk_common_OSLESMediaPlayer_releaseEngine
  (JNIEnv *, jclass);

/*
 * Class:     com_fitmix_sdk_common_OSLESMediaPlayer
 * Method:    createAudioPlayer
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_fitmix_sdk_common_OSLESMediaPlayer_createAudioPlayer
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_fitmix_sdk_common_OSLESMediaPlayer
 * Method:    releaseAudioPlayer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fitmix_sdk_common_OSLESMediaPlayer_releaseAudioPlayer
  (JNIEnv *, jclass);

/*
 * Class:     com_fitmix_sdk_common_OSLESMediaPlayer
 * Method:    play
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fitmix_sdk_common_OSLESMediaPlayer_play
  (JNIEnv *, jclass);

/*
 * Class:     com_fitmix_sdk_common_OSLESMediaPlayer
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fitmix_sdk_common_OSLESMediaPlayer_stop
  (JNIEnv *, jobject);

/*
 * Class:     com_fitmix_sdk_common_OSLESMediaPlayer
 * Method:    pause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fitmix_sdk_common_OSLESMediaPlayer_pause
  (JNIEnv *, jclass);

/*
 * Class:     com_fitmix_sdk_common_OSLESMediaPlayer
 * Method:    isPlaying
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_fitmix_sdk_common_OSLESMediaPlayer_isPlaying
  (JNIEnv *, jobject);

/*
 * Class:     com_fitmix_sdk_common_OSLESMediaPlayer
 * Method:    seekTo
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_fitmix_sdk_common_OSLESMediaPlayer_seekTo
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_fitmix_sdk_common_OSLESMediaPlayer
 * Method:    getDuration
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_fitmix_sdk_common_OSLESMediaPlayer_getDuration
  (JNIEnv *, jobject);

/*
 * Class:     com_fitmix_sdk_common_OSLESMediaPlayer
 * Method:    getPosition
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_fitmix_sdk_common_OSLESMediaPlayer_getPosition
  (JNIEnv *, jobject);

/*
 * Class:     com_fitmix_sdk_common_OSLESMediaPlayer
 * Method:    setPitch
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_fitmix_sdk_common_OSLESMediaPlayer_setPitch
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_fitmix_sdk_common_OSLESMediaPlayer
 * Method:    setRate
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_fitmix_sdk_common_OSLESMediaPlayer_setRate
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_fitmix_sdk_common_OSLESMediaPlayer
 * Method:    getRate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_fitmix_sdk_common_OSLESMediaPlayer_getRate
  (JNIEnv *, jclass);

/*
 * Class:     com_fitmix_sdk_common_OSLESMediaPlayer
 * Method:    setLoop
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_fitmix_sdk_common_OSLESMediaPlayer_setLoop
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_fitmix_sdk_common_OSLESMediaPlayer
 * Method:    setNoLoop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fitmix_sdk_common_OSLESMediaPlayer_setNoLoop
  (JNIEnv *, jobject);

/*
 * Class:     com_fitmix_sdk_common_OSLESMediaPlayer
 * Method:    createBufferQueueAudioPlayer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fitmix_sdk_common_OSLESMediaPlayer_createBufferQueueAudioPlayer
  (JNIEnv *, jclass);

/*
 * Class:     com_fitmix_sdk_common_OSLESMediaPlayer
 * Method:    createAssetAudioPlayer
 * Signature: (Landroid/content/res/AssetManager;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_fitmix_sdk_common_OSLESMediaPlayer_createAssetAudioPlayer
  (JNIEnv *, jclass, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
